import PageHero from "@/components/PageHero";
import Reveal from "@/components/Reveal";
import { site } from "@/content/site";

export default function PrivacyPolicy() {
  return (
    <>
      <PageHero eyebrow="Legal" title="Privacy Policy" lede="Last updated: October 30, 2025" />

      <section className="container-x pb-16">
        <Reveal>
          <div className="prose-legal mx-auto max-w-3xl space-y-6 text-muted">
            <p>Welcome to the BlueAngelClinical.com Site (the “Site”).</p>
            <p>
              This is the privacy notice of Blue Angel Clinical Partners, LLC (DBA
              “Blue Angel Clinical Partners”). In this document, “we”, “our”, or
              “us” refer to Blue Angel Clinical Partners, LLC.
            </p>
            <p>
              This notice informs you of our policy regarding all information that we
              record about you through our website. It sets out the conditions under
              which we may process any information that we collect from you, or that
              you provide to us. It covers information that could identify you
              (“personal information”) and information that could not. In the context
              of the law and this notice, “process” means collect, store, transfer,
              use or otherwise act on information.
            </p>
            <p>
              We take seriously the protection of your privacy and confidentiality.
              We understand that all visitors to our website are entitled to know that
              their personal data will not be used for any purpose unintended by them,
              and will not accidentally fall into the hands of a third party.
            </p>
            <p>
              We undertake to preserve the confidentiality of all information you
              provide to us, and hope that you reciprocate.
            </p>
            <p>
              We do not share, or sell, or disclose to a third party, any information
              collected through our website.
            </p>
            <p>
              If you join us as a patient or otherwise agree to our terms and
              conditions, a contract is formed between you and us. In order to carry
              out our obligations under that contract we must process the information
              you give us. Some of this information may be personal information. We
              process this information on the basis there is a contract between us, or
              that you have requested we use the information before we enter into a
              legal contract. We may use it to:
            </p>
            <ul className="ml-5 list-disc space-y-2">
              <li>verify your identity for security purposes</li>
              <li>sell products to you</li>
              <li>provide you with our services</li>
              <li>
                provide you with suggestions and advice on products, services and how
                to obtain the most from using our website
              </li>
            </ul>
            <p>
              Personal data submitted on this website will be used for the purposes
              specified in this privacy policy or in relevant parts of the website. We
              may use this information to:
            </p>
            <ul className="ml-5 list-disc space-y-2">
              <li>Send you general and marketing communications;</li>
              <li>Send you email notifications;</li>
              <li>To notify you about changes to our service;</li>
              <li>
                To ensure that content from our site is presented in the most
                effective manner for you and for your computer;
              </li>
              <li>
                Deal with enquiries and complaints made by or about you relating to
                the website.
              </li>
            </ul>
            <p>
              This website uses Google Analytics to help analyze how users use the
              site. The tool uses “cookies,” which are text files placed on your
              computer, to collect standard Internet log information and visitor
              behavior information in an anonymous form. The information generated by
              the cookie about your use of the website (including IP address) is
              transmitted to Google. This information is then used to evaluate
              visitors’ use of the website and to compile statistical reports on
              website activity.
            </p>
            <p>
              We will never (and will not allow any third party to) use the
              statistical analytics tool to track or to collect any Personally
              Identifiable Information (PII) of visitors to our site. Google will not
              associate your IP address with any other data held by Google. Neither we
              nor Google will link, or seek to link, an IP address with the identity
              of a computer user. We will not associate any data gathered from this
              site with any Personally Identifiable Information from any source, unless
              you explicitly submit that information via a fill-in form on our website.
            </p>
            <p>
              We record information such as your geographical location, your Internet
              service provider and your IP address. We also record information about
              the software you are using to browse our website, such as the type of
              computer or device and the screen resolution. This information is
              recorded by Google Analytics as well as via certain 3rd party plugins
              installed on our website. We use this information in aggregate to assess
              the popularity of the webpages on our website and how we perform in
              providing content to you.
            </p>
            <p>
              If you wish us to remove personally identifiable information from our
              systems, you may contact us at{" "}
              <a href="mailto:joseph@blueangelclinical.com" className="text-azure underline">
                joseph@blueangelclinical.com
              </a>
              . When we receive any request to access, edit or delete personal
              identifiable information we shall first take reasonable steps to verify
              your identity before granting you access or otherwise taking any action.
              This is important to safeguard your information.
            </p>
            <p>
              Our privacy policy has been compiled so as to comply with the law of
              every country or legal jurisdiction in which we aim to do business. If
              you think it fails to satisfy the law of your jurisdiction, we would like
              to hear from you.
            </p>
            <p>
              However, ultimately it is your choice as to whether you wish to use our
              website. If you have any questions regarding our privacy policy, please
              contact us at{" "}
              <a href={`mailto:${site.email}`} className="text-azure underline">
                {site.email}
              </a>
              .
            </p>
          </div>
        </Reveal>
      </section>
    </>
  );
}
